remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Gluc-Cog Final
description: Does sugar boost your cognition? Here is the scoop on my research project that attempts to answer this question. 